#!/usr/bin/env python3
"""
==============================================================================
Project: System Call Demonstration and Monitoring System
Web Dashboard Application Backend (Flask)
Course:  Operating Systems and Systems Programming (25CS2104E)
Team 18: Akhil AD, Revanth Reddy, Advik | Faculty: Dr. K. Hema
==============================================================================
"""

import os
import sys
import re
import json
import subprocess
from flask import Flask, render_template, jsonify, request

app = Flask(__name__)

# Base directory paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TRACES_DIR = os.path.join(BASE_DIR, "traces")

def get_wsl_path(win_path):
    """Converts a Windows path to WSL /mnt path."""
    clean_path = win_path.replace("\\", "/")
    if re.match(r"^[a-zA-Z]:", clean_path):
        drive = clean_path[0].lower()
        rest = clean_path[2:]
        return f"/mnt/{drive}{rest}"
    return clean_path

def run_project_command(cmd):
    """
    Executes a shell command either inside WSL (if on Windows)
    or directly in bash (if already running in Linux).
    """
    if sys.platform.startswith("win"):
        wsl_dir = get_wsl_path(BASE_DIR)
        full_cmd = f"cd '{wsl_dir}' && {cmd}"
        process = subprocess.run(
            ["wsl", "bash", "-c", full_cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace"
        )
    else:
        full_cmd = f"cd '{BASE_DIR}' && {cmd}"
        process = subprocess.run(
            ["bash", "-c", full_cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace"
        )
    return process.returncode, process.stdout

def parse_trace_summary():
    """Parses traces/trace_summary.log generated by strace -c"""
    summary_path = os.path.join(TRACES_DIR, "trace_summary.log")
    if not os.path.exists(summary_path):
        return {"calls": [], "total_calls": 0, "total_errors": 0}

    calls = []
    total_calls = 0
    total_errors = 0

    with open(summary_path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines()

    table_started = False
    for line in lines:
        if "------" in line:
            table_started = True
            continue
        if not table_started or not line.strip():
            continue

        parts = line.split()
        if len(parts) >= 6 and parts[-2] == "total":
            continue
        elif len(parts) == 6:
            # Format: %time seconds usecs/call calls errors syscall
            try:
                calls.append({
                    "percent_time": float(parts[0]),
                    "seconds": float(parts[1]),
                    "usecs_call": int(parts[2]),
                    "calls": int(parts[3]),
                    "errors": int(parts[4]),
                    "syscall": parts[5]
                })
                total_calls += int(parts[3])
                total_errors += int(parts[4])
            except (ValueError, IndexError):
                pass
        elif len(parts) == 5:
            # Format when errors is 0 (blank): %time seconds usecs/call calls syscall
            try:
                calls.append({
                    "percent_time": float(parts[0]),
                    "seconds": float(parts[1]),
                    "usecs_call": int(parts[2]),
                    "calls": int(parts[3]),
                    "errors": 0,
                    "syscall": parts[4]
                })
                total_calls += int(parts[3])
            except (ValueError, IndexError):
                pass

    return {
        "calls": sorted(calls, key=lambda x: x["calls"], reverse=True),
        "total_calls": total_calls,
        "total_errors": total_errors
    }

def parse_trace_filtered():
    """Parses traces/trace_filtered.log into individual syscall events"""
    filtered_path = os.path.join(TRACES_DIR, "trace_filtered.log")
    if not os.path.exists(filtered_path):
        return []

    events = []
    with open(filtered_path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("+++") or line.startswith("---"):
                continue

            pid = "main"
            pid_match = re.match(r"^(\d+)\s+(.*)$", line)
            if not pid_match:
                pid_match = re.match(r"^\[pid\s+(\d+)\]\s+(.*)$", line)

            if pid_match:
                pid = pid_match.group(1)
                line = pid_match.group(2)

            syscall_pattern = r"^([a-zA-Z0-9_]+)\((.*)\)\s+=\s+(-?[0-9a-fx?]+|\?)(.*)$"
            match = re.match(syscall_pattern, line)
            if not match:
                continue

            name = match.group(1)
            args = match.group(2)
            ret = match.group(3)
            extra = match.group(4).strip()

            is_error = ret.startswith("-") or "E" in extra
            error_name = ""
            if is_error and extra:
                err_m = re.search(r"(E[A-Z0-9]+)", extra)
                if err_m:
                    error_name = err_m.group(1)

            events.append({
                "pid": pid,
                "name": name,
                "args": args[:120],
                "ret": ret,
                "extra": extra,
                "is_error": is_error,
                "error_name": error_name
            })
    return events

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/status", methods=["GET"])
def get_status():
    bin_main = os.path.exists(os.path.join(BASE_DIR, "sys_call_demo"))
    bin_child = os.path.exists(os.path.join(BASE_DIR, "child_worker"))
    trace_avail = os.path.exists(os.path.join(TRACES_DIR, "trace_summary.log"))
    
    return jsonify({
        "status": "online",
        "platform": "WSL (Linux)" if sys.platform.startswith("win") else "Linux",
        "binaries_built": bin_main and bin_child,
        "traces_available": trace_avail,
        "team": "Team 18 (Section 03)",
        "members": ["Akhil AD (2520030423)", "Revanth Reddy (2520030424)", "Advik (2520039623)"],
        "faculty": "Dr. K. Hema"
    })

@app.route("/api/traces", methods=["GET"])
def get_traces():
    summary = parse_trace_summary()
    events = parse_trace_filtered()
    return jsonify({
        "summary": summary,
        "events": events[-50:],  # Return latest 50 events
        "errors": [e for e in events if e["is_error"]]
    })

@app.route("/api/run/<action>", methods=["POST"])
def run_action(action):
    command_map = {
        "build": "make clean && make all",
        "batch": "./sys_call_demo --batch",
        "file": "./sys_call_demo --file",
        "process": "./sys_call_demo --process",
        "error": "./sys_call_demo --error",
        "test": "make test",
        "trace": "make trace",
        "analyze": "make analyze",
        "clean": "make clean"
    }

    if action not in command_map:
        return jsonify({"success": False, "error": f"Invalid action '{action}'"}), 400

    cmd = command_map[action]
    code, output = run_project_command(cmd)

    # Clean ANSI escape sequences for web rendering (or keep them for terminal viewer)
    clean_output = output

    # Fetch updated trace stats if trace or analyze was run
    traces_data = None
    if action in ["batch", "trace", "analyze", "test"]:
        traces_data = {
            "summary": parse_trace_summary(),
            "events": parse_trace_filtered()[-30:]
        }

    return jsonify({
        "success": (code == 0),
        "return_code": code,
        "command": cmd,
        "output": clean_output,
        "traces": traces_data
    })

if __name__ == "__main__":
    port = 5000
    print("\n" + "=" * 70)
    print("  SYSTEM CALL DEMONSTRATION & MONITORING SYSTEM - WEB DASHBOARD")
    print(f"  Running on: http://localhost:{port}")
    print("=" * 70 + "\n")
    app.run(host="0.0.0.0", port=port, debug=False)
